### ISSUE TITLE
AdGroup::update error

### ISSUE THREAD

**Issue by Mirko09** [facebook/facebook-php-ads-sdk#119]
I am trying to update AdGroup::name.

$adgroup = new FacebookAds\Object\AdGroup('## here i set adgroup id ##');
$adgroup->{\FacebookAds\Object\Fields\AdGroupFields::NAME} = 'new name';
$adgroup->update();

And I get error 'Empty Response'
*Fatal error: Uncaught exception 'FB\Http\Exception\EmptyResponseException' with message 'Empty Response'*

But AdGroup::name is updated successfully.

I try SDK 2.3.0 and 2.4.1.

I can to use read(), but I can't to use update() and create().

How to fix it?

**Comment by pruno** [comment]
@Mirko09,

this seems to be an issue related to the API rather than the SDK, if this is not transient please open a bug here: https://developers.facebook.com/bugs/

PS: to be sure whether the issue is in the SDK, you can use the CurlLogger to generate an equivalent cURL call and perform it from the shell:

(this will dump to stdout)

~~~php
Api::init(...)->setLogger(new CurlLogger(STDOUT));
~~~
