### ISSUE TITLE
bid_type is missed form AdGroupFields

### ISSUE THREAD

**Issue by d3m3tr1s** [facebook/facebook-php-ads-sdk#135]
Hello, and thank you for your hard work on SDK

Notice some issue:
this documentation references that bid_type should be accessible for the AdGroup
while there is not such param in the

https://github.com/facebook/facebook-php-ads-sdk/blob/master/src/FacebookAds/Object/Fields/AdGroupFields.php

several other are missed too (e.g. bid_info)

Thank you.

**Comment by pruno** [comment]
Hi @d3m3tr1s,

bid_info and bid_type where deprecated in v2.4 (https://developers.facebook.com/docs/marketing-api/changelog#v2_4).

due to some niche, legacy ads these fields are not 100% extinct for compatibility reason, but you can't use them for update or create and unless your ads are in this niche category, you won't be able to read them neither. We decided to kill them in the SDK to limit confusion.

i know some other fields might me missing, and we are currently working on a solution to avoid this discrepancies.

Hope this explains it

**Comment by d3m3tr1s** [comment]
Thank you pruno and my apologizes for taking your time, missed that fact
