### ISSUE TITLE
Campaign::STATUS

### ISSUE THREAD

**Issue by fdask** [facebook/facebook-php-ads-sdk#138]
The docs for v2.5 on Facebook (https://developers.facebook.com/docs/marketing-api/reference/ad-campaign-group) references a CampaignFields::STATUS constant, but in the latest 2.5.0 code, I'm not seeing the value in the php-ads-sdk/src/FacebookAds/Object/CampaignFields.php file!

Here is the sample FB provides::

$campaign = new Campaign(null, $account_id);
$campaign->setData(array(
    CampaignFields::NAME => 'my campaign',
    CampaignFields::STATUS => Campaign::STATUS_PAUSED,
    CampaignFields::OBJECTIVE => 'PAGE_LIKES',
  ));

$campaign->create();

The version of the SDK I'm using is the latest from Composer...

**Comment by pruno** [comment]
Hi @fdask,

status is not a field of the object since v2.5.
We are in the process of updating that documentation page, here is how to do that:

~~~php
use FacebookAds\Object\Campaign;
use FacebookAds\Object\Fields\CampaignFields;

$campaign = new Campaign(null, $account_id);
$campaign->setData(array(
  CampaignFields::NAME => 'my campaign',
  CampaignFields::OBJECTIVE => 'PAGE_LIKES',
));

$campaign->create(array(
  AdCampaign::STATUS_PARAM_NAME => AdCampaign::STATUS_PAUSED,
));
~~~

To read the status:

~~~php
use FacebookAds\Object\Campaign;
use FacebookAds\Object\Fields\CampaignFields;

$campaign = new Campaign('<CAMPAIGN_ID>');
$adset->read(array(
  CampaignFields::CONFIGURED_STATUS,
  CampaignFields::EFFECTIVE_STATUS,
));
~~~

Hope this helps
