### ISSUE TITLE
Instagram ads unsupported on 2.4.* of SDK

### ISSUE THREAD

**Issue by bjeavons** [facebook/facebook-php-ads-sdk#141]
Trying to set 'instagram_actor_id' on AdCreative throws exception `Exception: instagram_actor_id is not a field of FacebookAds\Object\AdCreative`

https://github.com/facebook/facebook-php-ads-sdk/commit/68620a64473fb92f3815ba261200aa39662fc39a added AdCreativeField const INSTAGRAM_ACTOR_ID but that field is not available in SDK version 2.4.2

According to [FB API docs](https://developers.facebook.com/docs/marketing-api/guides/instagramads/v2.4#creative) this field is allowed on v2.4 of adcreative so can you tag a 2.4.3 of the SDK with this field?

**Comment by pruno** [comment]
@bjeavons,

As a release strategy, we don't apply additive changes to older versions of the SDK. While upgrading to 2.5 is the suggested path here. I do understand that it might not be your top priority now. Since v2.4 will be deprecated at the next cycle (v2.6 launch), as a temporary solution you may fork the repo and apply 68620a6 there until you will have time to upgrade to 2.5

**Comment by bjeavons** [comment]
@pruno, thanks for the response, however from an enduser standpoint that's frustrating to hear because it goes against what the larger FB ecosystem is saying about API versions, that v2.4 is supported right now. Why is this official SDK going against that statement? I don't see how this is an "additive change" either, this is a bug in the SDK and should be fixed as other bugs.
