### ISSUE TITLE
Unable to create additional Lookalike Audience 

### ISSUE THREAD

**Issue by vtalotlinx** [facebook/facebook-php-ads-sdk#181]
My request looks like this: 

curl \
  -F 'name=Lookalike (US, 5%) - ROH Main' \
  -F 'subtype=LOOKALIKE' \
  -F 'origin_audience_id=REMOVED' \
  -F 'lookalike_spec={"type":"reach","country":"US","ratio":CUSTOM_PERCENTAGE}' \
  -F 'access_token=REMOVED' \
  -F 'appsecret_proof=REMOVED' \
  https://graph.facebook.com/v2.5/REMOVED/customaudiences

I want to create 1%, 5% and 9% Lookalike audiences. The code works with only the first call. For example when I run the script with ratio = 0.09, it works; Then I run it again with ratio=0.05, it won't work but return me this error message: 

{"error":{"message":"(#2654) Can\u2019t Create a Duplicate Lookalike: You've already created a lookalike audience with the same source, country and size. Please try using a different source or different specifications.","type":"OAuthException","code":2654,"fbtrace_id":"A2IzZ\/JdRfk"}}

Could anyone help me with this please? I created audiences based on different ratios? 

Thank you in advance.

**Comment by duliomatos** [comment]
Hey @vtalotlinx, I'll close the issue here as it doesn't seem like a bug in the SDK, as you're using curl directly. But yes, you should be able to create audiences with different percentages but only one for each ratio/country/type combination, I would list all the audiences to make sure another person did not create an audience with the same ratio you're trying in this same ad account. If after that verification it looks like a bug pls report here https://developers.intern.facebook.com/bugs/

Best!
