### ISSUE TITLE
Uncaught InvalidArgumentException: ad_id is not a field of FacebookAds\Object\Lead

### ISSUE THREAD

**Issue by plasticbrain** [facebook/facebook-php-ads-sdk#204]
Up until a couple of days ago we were able to pull the Ad ID and Form ID from the `Lead` API call (as described in the docs here: https://developers.facebook.com/docs/marketing-api/guides/lead-ads/webhooks/v2.6). However, now I'm getting an error :

```
[16-Apr-2016 01:40:51 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: ad_id is not a field of FacebookAds\Object\Lead in fbleads/vendor/facebook/php-ads-sdk/src/FacebookAds/Object/AbstractObject.php:49
Stack trace:
#0 /redacted/file.php(433): FacebookAds\Object\AbstractObject->__get('ad_id')
#1 /redacted/file2.php(54): Plasticbrain\FBLeads\FBLeads->get_lead(########)
#2 {main}
  thrown in fbleads/vendor/facebook/php-ads-sdk/src/FacebookAds/Object/AbstractObject.php on line 49

```

Were there any recent breaking changes that would have caused this? I didn't see anything in https://github.com/facebook/facebook-php-ads-sdk/commit/81ead689696838080f3607e318503316e8859a0c 

Thank you

**Comment by duliomatos** [comment]
Hey @plasticbrain, will check this out. Can you tell me if which release version you're using, or if you're using master?

**Comment by duliomatos** [comment]
AD_ID was missing, reported here [Bug 247345592275817](https://developers.facebook.com/bugs/247345592275817/) and fixed in this commit https://github.com/facebook/facebook-php-ads-sdk/commit/1754dac1fe43d9954058e8289db5bd4a318b883c. It's on `master` and release versions [2.5.2] (../releases/tag/2.5.2) and [2.6.0](../releases/tag/2.6.0). Closing for now.
