### ISSUE TITLE
Why is there a mix of skds on the marketing API page?

### ISSUE THREAD

**Issue by gugaiz** [facebook/facebook-php-ads-sdk#281]
When reading the Marketing API page, there are code examples using the php-ads-sdk but some other examples using the graph-sdk... I am not sure why facebook mix all that.. If we can do everything with the graph sdk, which is the idea of the php-ads-sdk?

Examples..
https://developers.facebook.com/docs/marketing-api/reference/ad-account (Ads API PHP SDK)
https://developers.facebook.com/docs/marketing-api/reference/ad-account/campaignsbylabels/ (Graph API PHP SDK. It is possible to use getCampaignsByLabels() on the Ads API SDK but they used the other SDK instead, not sure why)

**Comment by daphyFB** [comment]
Thanks for report Ads API SDK issues.

All Facebook APIs are graph APIs, including Ads APIs, which means you could also use Graph API SDKs to do any Ads API calls. In fact, you can just use simple cURL or any other http requests to call our APIs. However, Ads API SDK also contains Ads object models which makes it easier and more robust to interact with those ads objects, instead of dealing with JSON directly.

The main reason we have two sets of SDKs is because we have different target users. Most of our Ads API SDK users run those APIs locally (or at their server side) and don't need to have the whole package of Graph API SDKs, which is different than Graph API SDK user scenarios.

Hope this answers your question!
