### ISSUE TITLE
Breaking changes in 2.8.2

### ISSUE THREAD

**Issue by swordbeta** [facebook/facebook-php-ads-sdk#303]
Why are there breaking changes in 2.8.2? Looks like we can't use 2.8.* but have to lockdown to certain versions if there are breaking changes introduced in minor patches.

What makes this even more weird is that there is no documentation.

**Comment by JiamingFB** [comment]
Hi @swordbeta 

Thanks for the feedback.

We shouldn't have introduced breaking changes in 2.8.2 release and looks like we made a mistake. We're sorry about that. Since v2.9 is released in the repo, we probably won't go back and fix for v2.8.

Our versioning is different from the MAJOR.MINOR.RELEASE versioning in that we do have breaking changes during MINOR change (e.g. 2.8 -> 2.9) because our server API has breaking changes during MINOR version update. But RELEASE changes shouldn't have breaking changes.
