### ISSUE TITLE
getLeads()  SORT

### ISSUE THREAD

**Issue by johnnykatz** [facebook/facebook-php-ads-sdk#309]
Hi!
I have a problem to sort the data I get. Someone can help me, I did not find documentation on the subject. thank you very much.

I have this but it does not work.

` $leads = $form->getLeads(array(), array(
                    AdReportRunFields::FILTERING => array(
                        array(
                            'field' => 'time_created',
                            'operator' => 'GREATER_THAN',
                            'value' => $time_from,
                        ),
                    ),
                    AdReportRunFields::SORT => array(
                        array(
                            'field' => 'time_created',
                            'operator' => 'GREATER_THAN',
                            'value' => 'ASC',
                        ),
                    ),

                ));`

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK issues.

From the code here:
https://github.com/facebook/facebook-php-ads-sdk/blob/master/src/FacebookAds/Object/Fields/AdReportRunFields.php#L101

You can see that the "sort" is a list of strings, not objects. Thus, instead of using
```
array(
  'field' => 'time_created',
  'operator' => 'GREATER_THAN',
  'value' => 'ASC',
),
```
please use a string: 
'time_created_ascending'

Please feel free to re-open this task if any further questions!

**Comment by EvandroBoeing** [comment]
Sorting 'time_created_ascending' is not working. The result list is always in the same order (from the newest to the oldest). Am I doing anything wrong?

$leads = $form->getLeads(array(), array(AdReportRunFields::FILTERING => array(array('field' => 'time_created','operator' => 'GREATER_THAN','value' => $time_from,),),AdReportRunFields::SORT => array('time_created_ascending'),'limit' => 50 ));
